name: "deploy-docker-image"
description: "Build and deploy a docker image to a registry"
inputs:
  images-repo:
    description: "The docker images repository"
    required: true
  region:
    description: "The AWS region"
    required: true
  working-dir:
    description: "The current working directory"
    required: true
  tag-name:
    description: "The tag name of the image"
    required: true
  service-repository-uri:
    description: "The URI of the docker image repository"
    required: true
  service-docker-file:
    description: "The location of the docker file of the service relative to the root of the github repository"
    required: true
runs:
  using: "docker"
  image: "docker://ioconnect/deploy-docker-image:1.0.4"
